default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  timeout: 5000
  pool: 5
  username: <%= Rails.application.credentials.dig(:db, :user) %>
  password: <%= Rails.application.credentials.dig(:db, :password) %>

development:
  <<: *default
  database: <%= "development#{ENV['DB_SUFFIX'].present? ? '_' : ''}#{ENV['DB_SUFFIX']}" %>

test:
  <<: *default
  database: <%= "test#{ENV['DB_SUFFIX'].present? ? '_' : ''}#{ENV['DB_SUFFIX']}" %>

production:
  <<: *default
  database: <%= "production#{ENV['DB_SUFFIX'].present? ? '_' : ''}#{ENV['DB_SUFFIX']}" %>
