default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['RAILS_DB_HOST'] %>
  timeout: 5000
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: <%= "development#{ENV['RAILS_DB_SUFFIX'] ? '_' : ''}#{ENV['RAILS_DB_SUFFIX']}" %>

test:
  <<: *default
  database: <%= "test#{ENV['RAILS_DB_SUFFIX'] ? '_' : ''}#{ENV['RAILS_DB_SUFFIX']}" %>

production:
  <<: *default
  database: <%= "production#{ENV['RAILS_DB_SUFFIX'] ? '_' : ''}#{ENV['RAILS_DB_SUFFIX']}" %>
